[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "anycrc"
version = "0.9.5"
description = "The fastest Python CRC Library"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["bitarray"]

[project.urls]
"Homepage" = "https://github.com/marzooqy/anycrc"

[tool.cibuildwheel]
build-frontend = "pip"
skip = "pp*"

#clang doesn't produce the correct CRC results in the current build
[tool.cibuildwheel.macos.environment]
CC = "gcc-14"