# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  windows_test:
    name: Test on windows-latest python ${{ matrix.python-version }} ${{ matrix.architecture }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        architecture: ["x64", "x86"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            python -m pip install . --config-settings compiler=mingw32
    - name: Run test
      run: python test.py
      
  mac_intel_test:
    name: Test on macos-13 python ${{ matrix.python-version }}
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Install gcc
      run: brew install gcc@13
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
            CC=gcc-13
            python -m pip install --upgrade pip
            python -m pip install .
    - name: Run test
      run: python test.py
      
  mac_silicon_test:
    name: Test on macos-14 python ${{ matrix.python-version }}
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Install gcc
      run: brew install gcc@13
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
            CC=gcc-13
            python -m pip install --upgrade pip
            python -m pip install .
    - name: Run test
      run: python test.py
      
  linux_test:
    name: Test on ubuntu-latest python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            python -m pip install .
    - name: Run test
      run: python test.py
    