# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }} python ${{ matrix.python-version }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        architecture: ["x64", "x86"]
        exclude:
          - os: ubuntu-latest
            architecture: "x86"
          - os: macos-13
            architecture: "x86"
          - os: macos-14
            architecture: "x86"
          - os: macos-14
            python-version: "3.7"
          - os: macos-14
            python-version: "3.8"
          - os: macos-14
            python-version: "3.9"
          - os: macos-14
            python-version: "3.10"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install . --config-settings compiler=mingw32
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Run test
      run: python test.py
